### ISSUE TITLE
Maybe should print PRL in another format?

### ISSUE THREAD

**Issue by naoliv** [daviswr/dhcpd.fingerprint#1]
Hi!

First, thanks a lot for this `.conf`!

I was taking a look at https://www.fingerbank.org/support/#/usage and it seems that it uses/needs the PRL in another format.
At https://github.com/daviswr/dhcpd.fingerprint/blob/a873b6a0d62cd1d6651e3bd7f489dac43d9a2dff/fingerprint.conf#L1919 it is encoding the PRLs in hexa, right?

Wouldn't it be better to use it as `binary-to-ascii(10, 8, ",", option dhcp-parameter-request-list)`, which seems to be the most common format?

Or maybe it could be logged both formats?

Thanks!

**Comment by daviswr** [comment]
Hi!

We discussed this a bit on #2, so I'm going to close this as well.

Cheers,

Wes
