### ISSUE TITLE
Fedora != Apple iOS 

### ISSUE THREAD

**Issue by xes** [daviswr/dhcpd.fingerprint#3]
Hi! Thank you for this nice fingerprint collecion!

I'm using this since some month and I would let you know that it's working great, except for the fingerprint of Fedora linux 32.
The device is identified as an "Apple iOS 15".

dhcp-op-req-string = "1:2:6:12:15:26:28:121:3:33:40:41:42:119:249:252:17";
prl = "1:2:6:c:f:1a:1c:79:3:21:28:29:2a:77:f9:fc:11";
ident = "Apple iOS 15";

Any idea how to fix this?

**Comment by daviswr** [comment]
I've seen DHCPD use whatever the last value was for the `ident` variable rather than log "[Unknown]" when it's unable to match on any class.

c1ac5f653ec7f414fccd864e46427289b65cec28 adds a PRL subclass match for what I've observed Fedora 32 and 36 to use. See if that helps?

**Comment by xes** [comment]
Thank you very much, now it matches the new subclass!

Since i'm using SytemRescue CD, and now it matches "ReactOS" definition I changed this:
subclass "PRL" 1:1c:2:3:f:6:c:2a { set ident = "SystemRescueCD"; }

I have no idea if this could be identified while keeping the ReactOS one. (if there is a real use case for this)

**Comment by daviswr** [comment]
This what I'm seeing for SystemRescueCD 9.04:

`PRL=1:2:6:c:f:1a:1c:79:3:21:28:29:2a:77:f9:fc:11 | Vendor=[None] | Hostname=sysrescue | Client=Fedora-based Linux`

What version are you using? Also: thinking the `sysrescue` hostname is probably unique to their Live CD, and that could help make a more-specific ident string.

Also, as I recently mentioned to someone else that had opened an issue & PR here, I don't _really_ maintain this much anymore, mainly for personal curiosity and I don't have access to the sort of environment I used to for finding new signatures and testing.

**Comment by daviswr** [comment]
And it looks like SystemRescueCD is based on Arch Linux, so I'm going to have to do some more digging.

**Comment by daviswr** [comment]
Try out 4baecff03c8628e82291bbe6cf28969155e7c72c ?

**Comment by xes** [comment]
Sorry for the late reply, I really don't want to bother you with new issues.
I notified what I found since I think that this fingerprint collection is really useful and a great and simple way to monitor what is happening into a wifi network. 
Thank you very much for your efforts and for the time you spend updating this!

**Comment by daviswr** [comment]
No worries :) I'm glad it's useful, the mess that it is!

I don't mind fixes here and there, but I'm not too interested in large changes at this point. Especially now that ISC has stopped maintaining dhcpd in favor of Kea.

Not that I don't occasionally put a weekend into it...
