### ISSUE TITLE
how to use the project?

### ISSUE THREAD

**Issue by hlguo** [daviswr/dhcpd.fingerprint#4]
how to use the project for C++ or Java, do you have sample code?

**Comment by daviswr** [comment]
This isn't code, it's config for ISC DHCPD that could be added-on to one's existing dhcpd.conf using the `include` statement. dhcpd will then produce two new types of log messages, one with prefix DHCPIDENT that will log what it can figure out about the DHCP client and optionally switchport, and another with prefix DHCPEXPIRE with an IP address whose lease expired.

DHCPIDENT log messages are Key=Value pairs that are pipe-character delimited. What you do with the resulting logs is up to you.

**Comment by hlguo** [comment]
do you have the config for ISC kea?

**Comment by daviswr** [comment]
No, sorry, I haven't done anything with Kea yet.
